### PR TITLE
Normalizing rights URLs

### PR DESCRIPTION
**Pull request by kelynch**

### CODE REVIEW

**Comment by bibliotechy** [comment]
@kelynch Do we no longer require all of those `normalize_global` and `normalize_facets` calls that are deleted here?

**Comment by kelynch** [comment]
We do, but not twice as they're currently happening.  Not sure how/when the redundancy was introduced but it does not appear to be necessary.  I also did remove normalize_global from the rights field, as that appears to be unnecessary given current workflows and this new functionality, but will be happy to introduce it back in and push to the branch for that field if desired.

**Comment by bibliotechy** [comment]
@kelynch Just double checking!

**Comment by kelynch** [comment]
😎  Cool.

**Comment by bibliotechy** [comment]
@kelynch So, I gave this another lok and I think those extra noramlize_globals need to be there because the difference between `normalize_global(doc, "//coverage")` and `normalize_global(doc, "//dc:coverage")` is important. One affects the blacklight presentation, the other affects what gets into the oai feed that is harvested by DPLA.

I'm going to make a pr that adds those back in because no one on the metadata team is double checking what is in the OAI feed vs what is in the DC feed.

**Comment by dorevabelfiore-temple** [comment]
Spoke to Leanne. We were discussing creating a checklist for testing so that we are sure to check both the front-end solr and the outbound OAI feed to DPLA (DC) post code changes.

**Pull request merged**
