### PR TITLE
Feature/dplah 93 default thumbnails

### PR DESCRIPTION
**Pull request by kelynch**

### CODE REVIEW

**Comment by bibliotechy** [comment]
@kelynch Can you suggest any example seeds I could harvest to test this with? I know Villanova, but it has so many records, it would take too long.

**Comment by kelynch** [comment]
Sure, there's A Celebration of Women Writers from Penn, base url: http://digital.library.upenn.edu/webbin/OAI-celebration, no setSpect.  There's between 400 - 500 records there.

You can also take a small seed, like Albright College Church Lantern Slides (which is 39 records) and change the common repository type to blank so it won't construct CONTENTdm thumbnails and will treat the records as if they have none.

**Comment by kelynch** [comment]
There's A Celebration of Women Writers from Penn, base url: http://digital.library.upenn.edu/webbin/OAI-celebration, no setSpect. There's between 400 - 500 records there.

You can also take a small seed, like Albright College Church Lantern Slides (which is 39 records) and change the common repository type to blank so it won't construct CONTENTdm thumbnails and will treat the records as if they have none.

**Comment by bibliotechy** [comment]
Alright looks good to me. Thanks!

**Pull request merged**
