### PR TITLE
Renamed to passthrough workflow per stakeholder request

### PR DESCRIPTION
**Pull request by kelynch**

### CODE REVIEW

**Comment by skng5** [comment]
:+1:

**Comment by skng5** [comment]
But there's a branch conflicts that must be resolved first.

**Comment by kelynch** [comment]
Will deal with and resubmit.

On Thu, Aug 6, 2015 at 1:55 PM, Steven Ng <notifications@github.com> wrote:

> But there's a branch conflicts that must be resolved first.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tulibraries/dplah/pull/37#issuecomment-128458629>.
>



-- 

Katherine Lynch, Senior Digital Library Applications Developer
Temple University Library (http://library.temple.edu)
Samuel L. Paley Library, Room 113, 1210 Polett Walk, Philadelphia, PA 19122
Tel: 215-204-2821 | Fax: 215-204-5201 | Email: katherine.lynch@temple.edu

**Comment by kelynch** [comment]
Fixed conflicts

**Comment by skng5** [comment]
:+1:

**Pull request merged**
