### PR TITLE
Migrate to blacklight 6

### PR DESCRIPTION
**Pull request by skng5**
Migration to Blacklight 6

### CODE REVIEW

**Comment by bibliotechy** [comment]
When I tried to deploy to vagrant, I get this error:

```
[dplah@localhost dplah]$ RAILS_ENV=production bundle exec rake assets:precompile --trace
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Execute assets:precompile
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/sass_processor.rb:278:in `sprockets_context'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/sass_processor.rb:124:in `asset_path'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/sass_processor.rb:200:in `font_path'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/script/tree/funcall.rb:155:in `block in _perform'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:108:in `block in with_function'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:135:in `with_frame'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:108:in `with_function'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/script/tree/funcall.rb:153:in `_perform'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/script/tree/node.rb:50:in `perform'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:416:in `visit_return'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/base.rb:36:in `visit'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:162:in `block in visit'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:79:in `block in with_base'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:135:in `with_frame'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:79:in `with_base'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:162:in `visit'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:10:in `visit'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/script/tree/funcall.rb:265:in `block (3 levels) in perform_sass_fn'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/script/tree/funcall.rb:265:in `each'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/script/tree/funcall.rb:265:in `block (2 levels) in perform_sass_fn'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/script/tree/funcall.rb:264:in `catch'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/script/tree/funcall.rb:264:in `block in perform_sass_fn'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:86:in `perform_arguments'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/script/tree/funcall.rb:261:in `perform_sass_fn'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/script/tree/funcall.rb:144:in `block in _perform'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:108:in `block in with_function'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:135:in `with_frame'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:108:in `with_function'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/script/tree/funcall.rb:143:in `_perform'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/script/tree/node.rb:50:in `perform'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/script/functions.rb:617:in `perform'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/script/functions.rb:2333:in `if'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/script/tree/funcall.rb:155:in `block in _perform'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:108:in `block in with_function'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:135:in `with_frame'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:108:in `with_function'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/script/tree/funcall.rb:153:in `_perform'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/script/tree/node.rb:50:in `perform'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/script/tree/funcall.rb:186:in `perform_arg'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/script/tree/funcall.rb:133:in `block in _perform'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/script/tree/funcall.rb:133:in `each'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/script/tree/funcall.rb:133:in `each_with_index'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/script/tree/funcall.rb:133:in `each'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/script/tree/funcall.rb:133:in `map'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/script/tree/funcall.rb:133:in `_perform'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/script/tree/node.rb:50:in `perform'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:402:in `visit_prop'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/base.rb:36:in `visit'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:162:in `block in visit'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:79:in `block in with_base'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:135:in `with_frame'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:79:in `with_base'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:162:in `visit'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:517:in `block (2 levels) in visit_directive'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:517:in `map'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:517:in `block in visit_directive'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:183:in `with_environment'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:516:in `visit_directive'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/base.rb:36:in `visit'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:162:in `block in visit'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:79:in `block in with_base'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:135:in `with_frame'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:79:in `with_base'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:162:in `visit'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:329:in `block (2 levels) in visit_import'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:329:in `map'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:329:in `block in visit_import'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:88:in `block in with_import'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:135:in `with_frame'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:88:in `with_import'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:326:in `visit_import'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/base.rb:36:in `visit'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:162:in `block in visit'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:79:in `block in with_base'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:135:in `with_frame'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:79:in `with_base'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:162:in `visit'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:329:in `block (2 levels) in visit_import'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:329:in `map'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:329:in `block in visit_import'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:88:in `block in with_import'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:135:in `with_frame'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:88:in `with_import'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:326:in `visit_import'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/base.rb:36:in `visit'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:162:in `block in visit'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:79:in `block in with_base'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:135:in `with_frame'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/stack.rb:79:in `with_base'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:162:in `visit'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/base.rb:52:in `map'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/base.rb:52:in `visit_children'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:171:in `block in visit_children'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:183:in `with_environment'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:170:in `visit_children'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/base.rb:36:in `block in visit'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:190:in `visit_root'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/base.rb:36:in `visit'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:161:in `visit'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:10:in `visit'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/root_node.rb:36:in `css_tree'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/tree/root_node.rb:20:in `render'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sass-3.5.5/lib/sass/engine.rb:290:in `render'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/sass_compressor.rb:48:in `call'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/sass_compressor.rb:28:in `call'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:142:in `block in find'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `each'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `stat_directory'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:227:in `stat_tree'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `each'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `each'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `logical_paths'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:140:in `find'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/home/dplah/.rbenv/versions/2.3.5/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/var/www/dplah/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/var/www/dplah/vendor/bundle/ruby/2.3.0/bin/rake:22:in `load'
/var/www/dplah/vendor/bundle/ruby/2.3.0/bin/rake:22:in `<top (required)>'
/home/dplah/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/home/dplah/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/home/dplah/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/home/dplah/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/home/dplah/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/dplah/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/dplah/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/dplah/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/home/dplah/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/dplah/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/home/dplah/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/home/dplah/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/home/dplah/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/home/dplah/.rbenv/versions/2.3.5/bin/bundle:22:in `load'
/home/dplah/.rbenv/versions/2.3.5/bin/bundle:22:in `<main>'
Tasks: TOP => assets:precompile
```
Looks like a [SO post suggests](https://stackoverflow.com/questions/33515497/rails-nomethoderror-undefined-method-for-nilnilclass-error-while-precompl) it is related to a CSS problem. Wanna dig through your CSS changes and see if anything looks suspect?

**Comment by skng5** [comment]
@bibliotechy I wonder if that might be due to changing the asset names to what's used in Blacklight 6, that is removing stuff like *.css.scss to just *.scss.

**Comment by skng5** [comment]
The problem appears to be with bootstrap-sprockets in `apps/assets/stylesheets/application.css`. If I comment out that import, it precompiles assets successfully.

**Comment by skng5** [comment]
@bibliotechy We're ready for another review.

**Pull request merged**
