### PR TITLE
Feature/dplah 9a harvest thumbnails enhancements

### PR DESCRIPTION
**Pull request by kelynch**

### CODE REVIEW

**Comment by skng5** [comment]
+1

**Comment by skng5** [comment]
I just noticed that it broke the oai_recs and provider view specs. I these are related to new/modified fields.

**Comment by kelynch** [comment]
Cool, I'll update the specs in DPLAH-9b ASAP.

**Comment by kelynch** [comment]
On closer look it seems like this might not be related as the tests are still failing, but I'm working on this now to see what's up.

**Pull request merged**
